# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    command: tail -f /dev/null

volumes:
  postgres_data:
